# -*- coding: utf-8 -*-
"""figure_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQFqBvSKMo4yMqX-DK5z2fJbN-2NHrFr
"""

import pandas as pd

# Load data
data = pd.read_csv('sigmodcom.csv')

# Ensure 'year' is a numeric type and drop any non-numeric or missing values
data['year'] = pd.to_numeric(data['year'], errors='coerce')
data = data.dropna(subset=['year'])

# Convert 'year' to integer
data['year'] = data['year'].astype(int)

results = []

years_range = range(1991, data['year'].max() - 4)
for start_year in years_range:
    end_year = start_year + 4
    count = data[(data['year'] >= start_year) & (data['year'] <= end_year)].shape[0]
    results.append({'Start Year': start_year, 'End Year': end_year, 'Publication Count': count})

# Convert the list of dictionaries into a DataFrame
results_df_com = pd.DataFrame(results)

import pandas as pd

# Load data
data = pd.read_csv('sigmodedu.csv')

# Ensure 'year' is a numeric type and drop any non-numeric or missing values
data['year'] = pd.to_numeric(data['year'], errors='coerce')
data = data.dropna(subset=['year'])

# Convert 'year' to integer
data['year'] = data['year'].astype(int)

results = []

years_range = range(1991, data['year'].max() - 4)
for start_year in years_range:
    end_year = start_year + 4
    count = data[(data['year'] >= start_year) & (data['year'] <= end_year)].shape[0]
    results.append({'Start Year': start_year, 'End Year': end_year, 'Publication Count': count})

# Convert the list of dictionaries into a DataFrame
results_df_edu = pd.DataFrame(results)

import pandas as pd
import matplotlib.pyplot as plt

# Merge the DataFrames on the 'Start Year' and 'End Year' column
df = pd.merge(results_df_edu, results_df_com, on=['Start Year','End Year'], suffixes=('_edu', '_com'))

plt.figure(figsize=(14, 8))
bar_width = 0.4
bar1 = [i for i in range(len(df['Start Year']))]
bar2 = [i + bar_width for i in bar1]

# Plotting
plt.bar(bar1, df['Publication Count_edu'], width=bar_width, label='Edu Count', color='b')
plt.bar(bar2, df['Publication Count_com'], width=bar_width, label='Com Count', color='r')

# Adding Xticks
plt.xlabel('Year Range')
plt.ylabel('Number of SIGMOD Publications')
plt.title('Number of SIGMOD Publications from industry[com] and academia[edu] in 5 Year windows')
plt.xticks([r + bar_width/2 for r in range(len(df['Start Year']))], [f"{x}-{y}" for x, y in zip(df['Start Year'], df['End Year'])], rotation=45)

# Adding legend
plt.legend()

# Show the plot
plt.show()